[package]
name = "file-store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
commons.workspace = true
memmap2.workspace = true
ownedbytes.workspace = true
uuid.workspace = true
tracing.workspace = true
