[package]
name = "leechy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
kuchiki = { path = "../kuchiki" }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
toml.workspace = true
